apiVersion: v2
name: ecommerce-app
description: A Helm chart for e-commerce microservices application
type: application
version: 1.0.0
appVersion: "1.0"
keywords:
  - ecommerce
  - microservices
  - kubernetes
maintainers:
  - name: DevOps Team
    email: devops@ecommerce.local
home: https://github.com/ecommerce/lifecycle-mgmt
sources:
  - https://github.com/ecommerce/lifecycle-mgmt
dependencies: []
