---
# Canary Deployment Strategy for Frontend using Flagger
# This requires Flagger and Prometheus to be installed
# Install Flagger: helm repo add flagger https://flagger.app && helm install flagger flagger/flagger
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: frontend
  namespace: ecommerce
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  progressDeadlineSeconds: 60
  service:
    port: 80
  analysis:
    interval: 30s
    threshold: 5
    maxWeight: 50
    stepWeight: 10
    metrics:
    - name: request-success-rate
      thresholdRange:
        min: 99
      interval: 1m
    - name: request-duration
      thresholdRange:
        max: 500
      interval: 1m
    webhooks:
    - name: smoke-tests
      url: http://flagger-loadtester/
      timeout: 30s
      metadata:
        type: smoke
        cmd: "curl -sd 'test' http://frontend/health"
  # Specify the new version for canary deployment
  skipAnalysis: false

---
# Blue-Green Deployment Strategy for API Gateway
# This is a manual blue-green setup using labels
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-blue
  namespace: ecommerce
  labels:
    app: api-gateway
    tier: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: api-gateway
    version: v1

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-green
  namespace: ecommerce
  labels:
    app: api-gateway
    tier: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: api-gateway
    version: v2

---
# Blue deployment (current stable version)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-blue
  namespace: ecommerce
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
      version: v1
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: nginx:1.23-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      terminationGracePeriodSeconds: 30

      volumes:
      - name: nginx-config
        configMap:
          name: api-gateway-config

---
# Green deployment (new version - ready to switch to)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-green
  namespace: ecommerce
  labels:
    app: api-gateway
    version: v2
spec:
  replicas: 0  # Initially scaled to 0, increase when ready to switch
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
      version: v2
  template:
    metadata:
      labels:
        app: api-gateway
        version: v2
    spec:
      containers:
      - name: api-gateway
        image: nginx:1.24-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP

        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2

        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 15
          timeoutSeconds: 3
          failureThreshold: 3

        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

      terminationGracePeriodSeconds: 30

      volumes:
      - name: nginx-config
        configMap:
          name: api-gateway-config
