{{- if .Values.apiGateway.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-gateway
    tier: api
spec:
  type: {{ .Values.apiGateway.service.type }}
  ports:
  - name: http
    port: {{ .Values.apiGateway.service.port }}
    targetPort: {{ .Values.apiGateway.service.targetPort }}
    protocol: TCP
  selector:
    app: api-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: {{ .Values.global.namespace }}
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: {{ .Values.apiGateway.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: {{ .Values.apiGateway.image.repository }}:{{ .Values.apiGateway.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.apiGateway.service.targetPort }}
          protocol: TCP

        startupProbe:
          httpGet:
            path: /health
            port: {{ .Values.apiGateway.service.targetPort }}
          initialDelaySeconds: {{ .Values.apiGateway.healthChecks.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiGateway.healthChecks.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.apiGateway.healthChecks.startup.timeoutSeconds }}
          failureThreshold: {{ .Values.apiGateway.healthChecks.startup.failureThreshold }}

        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.apiGateway.service.targetPort }}
          initialDelaySeconds: {{ .Values.apiGateway.healthChecks.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiGateway.healthChecks.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.apiGateway.healthChecks.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.apiGateway.healthChecks.readiness.failureThreshold }}

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.apiGateway.service.targetPort }}
          initialDelaySeconds: {{ .Values.apiGateway.healthChecks.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.apiGateway.healthChecks.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.apiGateway.healthChecks.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.apiGateway.healthChecks.liveness.failureThreshold }}

        env:
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: PRODUCT_SERVICE_URL
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: service-urls
              key: ORDER_SERVICE_URL

        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

        resources:
          requests:
            cpu: {{ .Values.apiGateway.resources.requests.cpu }}
            memory: {{ .Values.apiGateway.resources.requests.memory }}
          limits:
            cpu: {{ .Values.apiGateway.resources.limits.cpu }}
            memory: {{ .Values.apiGateway.resources.limits.memory }}

      volumes:
      - name: nginx-config
        configMap:
          name: api-gateway-config

      terminationGracePeriodSeconds: 30

{{- if .Values.apiGateway.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: {{ .Values.apiGateway.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.apiGateway.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.apiGateway.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
