{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
    tier: presentation
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.targetPort }}
    protocol: TCP
  selector:
    app: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app: frontend
    version: v1
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        version: v1
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.frontend.service.targetPort }}
          protocol: TCP

        startupProbe:
          httpGet:
            path: /health
            port: {{ .Values.frontend.service.targetPort }}
          initialDelaySeconds: {{ .Values.frontend.healthChecks.startup.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.healthChecks.startup.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.healthChecks.startup.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.healthChecks.startup.failureThreshold }}

        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.frontend.service.targetPort }}
          initialDelaySeconds: {{ .Values.frontend.healthChecks.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.healthChecks.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.healthChecks.readiness.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.healthChecks.readiness.failureThreshold }}

        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.frontend.service.targetPort }}
          initialDelaySeconds: {{ .Values.frontend.healthChecks.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.frontend.healthChecks.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.frontend.healthChecks.liveness.timeoutSeconds }}
          failureThreshold: {{ .Values.frontend.healthChecks.liveness.failureThreshold }}

        resources:
          requests:
            cpu: {{ .Values.frontend.resources.requests.cpu }}
            memory: {{ .Values.frontend.resources.requests.memory }}
          limits:
            cpu: {{ .Values.frontend.resources.limits.cpu }}
            memory: {{ .Values.frontend.resources.limits.memory }}

      terminationGracePeriodSeconds: 30

{{- if .Values.frontend.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: frontend-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: {{ .Values.frontend.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.frontend.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontend.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
{{- end }}
